name: museumapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.6
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  audioplayers: ^6.0.0
  webview_flutter: ^4.7.0
  http: ^1.2.1
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  fonts:
    - family: Orelega One
      fonts:
        - asset: fonts/OrelegaOne-Regular.ttf
  uses-material-design: true
  assets:
    - images/
